---
- name: Provisioning a new EC2 instance and security group
  hosts: localhost
  connection: local
  gather_facts: False
  tags: provisioning

  pre_tasks:
    - name: Gather facts
      setup:
    - name: Print Python version
      debug:
        msg: "Using Python {{ ansible_python_version }}"
    - name: Install dependencies
      ansible.builtin.pip:
        name: "{{ item }}"
        executable: /usr/bin/python3.10
      loop:
        - boto3
        - botocore

  vars:
    ansible_python_interpreter: /usr/bin/python3.10
    keypair: devops
    instance_type: t2.micro
    image_id: ami-05fb0b8c1424f266b  # AMI ID
    wait: yes
    group: webserver
    count: 1
    region: us-east-2
    vpc_id: vpc-0657d78c02ef86ae1
    security_group_id: sg-095a9891af40155a0
    tag_name:
      Name: demo-ec2

  tasks:
    - name: Launch the new EC2 Instance
      amazon.aws.ec2_instance:
        vpc_subnet_id: "{{ vpc_id }}"
        security_group: "{{ security_group_id }}"
        instance_type: "{{ instance_type }}"
        image_id: "{{ image_id }}"
        wait: "{{ wait }}"
        region: "{{ region }}"
        key_name: "{{ keypair }}"
        count: "{{ count }}"
        tags: "{{ tag_name }}"
        user_data: |
          #!/bin/bash
          sudo apt update -y
          sudo apt install docker.io -y
          sudo systemctl start docker
          sudo systemctl enable docker
          docker run -d --name game -p 8080:80 sirisha7474/myapp
      register: ec2
